name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout
        run: actions/checkout@master

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build style
        run: gulp makeTheme

      # - name: Deploy theme
      #   uses: easingthemes/ssh-deploy@v2.0.7
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
      #     SOURCE: "lib/"
      #     REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
      #     REMOTE_USER: ${{ secrets.DEPLOY_USER }}
      #     TARGET: ${{ secrets.DEPLOY_THEME_DIR }}
